[meta]
name = "All Decoration Unlocker"
author = "Moski & Miss & Beu & Greep"
category = "Map Editor"
perms = "paid"
siteid = 173

version = "2.0"

blocks = [ "Plugin_DecorationUnlocker" ]

[script]
imports = [ "Patch.as", "Permissions.as" ]
